name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test repo access
        run: |
          curl -I -v https://repo.srnyx.com/snapshots/xyz/srnyx/java-utilities/4a0f974/java-utilities-4a0f974.pom
          curl -L -v https://repo.srnyx.com/snapshots/xyz/srnyx/java-utilities/4a0f974/java-utilities-4a0f974.pom
